

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - 'keycloak-db-data:/var/lib/postgresql/data'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    ports:
      - '9090:8080'

  account-service-db:
    image: postgres:15
    container_name: account-service-db
    environment:
      POSTGRES_DB: account_service
      POSTGRES_USER: account_service
      POSTGRES_PASSWORD: account_service_pass
    ports:
      - '5432:5432'
    volumes:
      - 'account-service-db-data:/var/lib/postgresql/data'

volumes:
  keycloak-db-data:
  account-service-db-data: