spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: account_service
    password: account_service_pass

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/budget-roots

budget-roots:
  keycloak:
    url: http://localhost:9090
    realm: budget-roots
    admin-username: admin
    admin-password: admin
