spring:
  application:
    name: budget-roots-account-service

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600_000
      connection-timeout: 30_000
      max-lifetime: 1_800_000
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    open-in-view: false

