[versions]
kotlin = "2.1.10"
spring-boot = "3.5.0"
spring-dependency-management = "1.1.7"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
